### ISSUE TITLE
replace old ruby buildpack-packager with new go packager

### ISSUE THREAD

**Issue by gmllt** [orange-cloudfoundry/sidecars-buildpack#5]
See deprecation in ruby [buildpack-packager](https://github.com/cloudfoundry/buildpack-packager) [README.md](https://github.com/cloudfoundry/buildpack-packager/blob/master/README.md)

Link to new go [buildpack-packager](https://github.com/cloudfoundry/libbuildpack/tree/master/packager/buildpack-packager)

**Comment by romain-dartigues** [comment]
should be fixed in b52761cc96e3ccee4ec5307a6ece04cbd4afc26a and/or #22
